const labels = {
  account: {
    accountClosed: 'Rachunek zamknięty - brak możliwości edycji!',
    add: 'Dodaj rachunek',
    advanced: 'Wyszukiwanie zaawansowane',
    automatic: 'ostatnie ',
    choose: 'Proszę wybrać',
    closed: 'Stan rachunku',
    createXml: 'Wygeneruj plik',
    dateFrom: 'Data początkowa',
    dateTo: 'Data końcowa',
    download: 'Pobierz plik',
    edit: 'Edytuj rachunek',
    foundAutomatic: ' wyników',
    foundCustom: ' wyników z podanego zakresu',
    list: 'Lista rachunków - ',
    management: 'Zarządzanie rachunkami',
    modal: {
      accessories: 'Akcesoria',
      address: 'Numer przesyłki',
      amount: 'Kwota',
      book: 'Książki',
      car: 'Auta',
      cashTime: 'Data wpłaty',
      coach: 'Wagony',
      element: 'Elementy makiety',
      locs: 'Lokomotywy',
      receipt: 'Numer dokumentu',
      receiptTime: 'Data paragonu',
      recipient: 'Zamówienie',
      remarks: 'Uwagi',
      state: 'Rodzaj rachunku',
      type: 'Typ rachunku'
    },
    modalEdit: 'Zmodyfikuj istniejący rachunek',
    modalNew: 'Dodaj nowy rachunek',
    title: 'Manager rachunków Ad9BIS',
    type: 'Typ rachunku'
  },
  buttons: {
    clear: 'Usuń',
    close: 'Zamknij',
    edition: 'Edycja',
    even: 'Wyrównaj ilości',
    history: 'Historia',
    orderReturn: 'Powrót do zamówienia',
    restoreList: 'Powrót do listy',
    save: 'Zapisz',
    sendMail: 'Wyślij email',
    showMail: 'Zobacz treść'
  },
  customer: {
    email: 'Adres e-mail',
    emailError: 'Adres niepoprawny!',
    search: 'Wyszukaj',
    title: 'Manager klientów Ad9BIS'
  },
  login: {
    error: 'Dane niepoprawne!',
    login: 'Zaloguj',
    remember: 'Zapamiętaj',
    title: 'Panel CMS'
  },
  logout: 'Zostałeś skutecznie wylogowany',
  order: {
    amount: 'Kwota (zł):',
    choose: 'Proszę wybrać',
    chooseOrder: 'Wybierz zamówienie',
    chooseAction: 'Wybierz akcję',
    customer: 'Klient:',
    db: {
      new: 'nowy panel',
      old: 'stary panel'
    },
    deliveryHide: 'Schowaj numer',
    deliveryNumber: 'Prześlij numer wysyłki',
    deliveryNumberFill: 'Wprowadź numer',
    detailsDefault: 'Wybierz akcję i numer zamówienia',
    detailsHeader: 'Szczegóły zamówienia nr',
    edition: 'Pełna edycja',
    email: 'Adres e-mail:',
    evenHeader: 'Wyrównanie ilości produktów - zamówienie nr ',
    lastVoucher: 'Numer ostatniego kuponu:',
    noVoucher: 'Brak zamówień powyżej 50zł',
    summary: 'PODSUMOWANIE',
    title: 'Manager zamówień Ad9BIS',
    totalPaid: 'Suma produktów z wysyłką:',
    totalPaidDiscount: 'Suma z wysyłką po rabacie:',
    totalProduct: 'Suma wszystkich produktów:',
    totalProductDiscount: 'Suma po rabacie:',
    totalShipment: '',
    voucherNumber: 'Numer ostatniego kuponu:',
    voucherNumberAdd: 'Zwiększ numer',
    voucherNumberShort: 'Numer kuponu:',
    voucherNumberSubtract: 'Zmniejsz numer',
    voucherTitle: 'Wyniki wyszukiwania kuponów dla Klienta:'
  },
  placeholders: {
    ammount: 'Podaj kwotę',
    chooseNumber: 'Wybierz numer',
    deliverynumber: 'Numer przesyłki',
    description: 'Podaj opis',
    descriptionShort: 'Podaj krótki opis',
    email: 'Wpisz adres',
    link: 'Podaj link',
    login: 'Podaj login',
    metaDescription: 'Podaj meta-opis',
    metaTitle: 'Podaj meta-tytuł',
    name: 'Podaj nazwę',
    number: 'Podaj numer',
    password: 'Podaj hasło',
    price: 'Podaj cenę',
    quantity: 'Podaj ilość',
    remarks: 'Wpisz uwagi',
    tags: 'Podaj tagi (po przecinku)'
  },
  postal: {
    add: 'Dodaj kwotę',
    amountAfterChange: 'Kwota po zmianie',
    ammountNow: 'Kwota do zmiany',
    currentAmount: 'Bieżąca kwota:',
    history: 'Historia zmian (ostatnie 5 wpisów):',
    noAmount: 'Brak danych...',
    save: 'Zmień kwotę',
    subtract: 'Odejmij kwotę',
    title: 'Manager wysyłek Ad9BIS'
  },
  product: {
    addPrinting: 'Dodaj dokument',
    basicDisabled: 'Zmiana cen wyłącznie przez pełną edycję!',
    byId: 'Wyszukiwanie po ID:',
    byName: 'Wyszukiwanie po nazwie:',
    checkDiscount: 'Sprawdź rabat!',
    choose: 'Proszę wybrać',
    chooseCategory: 'Wybierz kategorię',
    chooseManufactorer: 'Wybierz producenta',
    deleteOrder: 'Usuń zamówienie',
    deletePrinting: 'Usuń plik',
    discount: ' - rabat wynosi: ',
    download: 'Pobierz',
    edition: {
      actions: 'Akcje:',
      active: 'Aktywność:',
      categories: 'Kategorie:',
      categoriesActive: 'Ilość aktywnych kategorii: ',
      condition: 'Stan:',
      deletePhotos: 'Usuń zdjęcia',
      description: 'Pełny opis:',
      descriptionShort: 'Krótki opis:',
      manufactorer: 'Producent:',
      metaDescription: 'Meta-opis produktu:',
      metaTitle: 'Meta-tytuł produktu:',
      name: 'Nazwa:',
      photos: 'Zdjęcia:',
      photosAmount: 'Ilość zdjęć: ',
      price: 'Cena:',
      priceNew: 'Cena (NP):',
      priceOld: 'Cena (SP):',
      quantity: 'Ilość:',
      setModified: 'Zapisz produkt jako podmieniony',
      tags: 'Tagi produktu:',
      toggle: 'Kliknij żeby wyświetlić (schować)',
      url: 'Link:'
    },
    editionBasic: 'Skrócona edycja',
    editionFull: 'Pełna edycja',
    editionTitle: 'Pełna edycja produktu ID: ',
    fileDesc: 'Opis dokumentu',
    fileName: 'Nazwa pliku',
    history: 'Historia',
    historyTitle: 'Historia zmian produktu ID: ',
    lastOrders: 'Najnowsze zamówienia:',
    modalTitle: 'Skrócona edycja produktu ID: ',
    modifiedEmpty: 'Obecnie brak produktów zmodyfikowanych',
    modifiedTitle: 'Lista podmienionych produktów',
    name: 'Nazwa produktu',
    newFile: 'Nowy dokument do wydruku',
    noHistory: 'Nie ma historii zmian żądanego produktu',
    noLastOrders: 'Obecnie brak nowych zamówień',
    noPrintings: 'Obecnie brak dokumentów do wydruku',
    otherManufactorer: 'Brak (inny producent)',
    panels: { new: 'Nowy panel', old: 'Stary panel' },
    priceNew: 'Cena nominalna: ',
    priceRealNew: 'Uwaga! Realna cena w nowym panelu to:',
    priceRealOld: 'Uwaga! Realna cena w starym panelu to:',
    printings: 'Dokumenty do wydruku:',
    quantityEqual: 'Ta sama ilość w obu panelach',
    quantityNotEqual: 'UWAGA - ilość w nowym panelu to: ',
    search: 'Wyszukaj',
    title: 'Manager produktów Ad9BIS'
  }
}
export default labels
